### ISSUE TITLE
Dependency on tools.cli-0.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by Haifen** [garypen/secret-santa#1]
Hi-
    I realize that secret-santa depends on tools.cli-0.2.0-SNAPSHOT and will not work with 0.1.0, but I'm unable to get 0.2.0-SNAPSHOT from any of the repositories in my default lein install (1.6.1.1).  Am I doing something wrong or missing something?  Did you build tools.cli from source and deploy it to your ~/.m2/repository?  Any help would be greatly appreciated.

```
    -Robin K.
```

Update --
Looks like tools.cli is out at 0.2.0.  Suggest changing the dependency to that.

```
    -Robin K.
```

**Comment by Haifen** [comment]
This is a separate issue, but it would appear tools.cli 0.2.0 has the same problem that 0.1.0 did "Exception in thread "main" clojure.lang.ArityException: Wrong number of args (2) passed to: PersistentVector" with tools.cli the third line down in the stacktrace.(above it is clojure.lang.AFn.invoke and above that is clojure.lang.AFn.throwArity).  If tools.cli 0.2.0 has the same problem as 0.1.0 that was fixed in one of the (less|more) recent versions of 0.2.0-SNAPSHOT, then the above bug is still slightly applicable, but this seems more like a different issue (and a more general one).

**Comment by garypen** [comment]
I'll look into the tools.cli "Wrong number of args" issue. The primary issue is resolved though since I have updated the dependency to "0.2.0". Jus so you know, I did build tools.cli from source and install as you describe.
